Add support for dt.timedelta to travel class
adamchainz/time-machine pull request #298
Opened 2022-11-03 01:33 UTC by AgDude

Adds support to pass a datetime.timedelta object to `travel`.

To avoid potential abuse this feature is blocked when already traveling, since the `shift` API would provide similar functionality and should be simpler.

fixes #38

2022-11-03 10:52 UTC, adamchainz requested changes
Thanks for working on this.

Please add docs and a release note. (And whenever opening PR's in open source.)

2022-11-03 10:52 UTC, adamchainz commented on src/time_machine/__init__.py
> +        if escape_hatch.is_travelling():
No need to use the escape hatch API internally
```suggestion
        if coordinates_stack:
```

2022-11-03 10:52 UTC, adamchainz commented on src/time_machine/__init__.py
> +                "Timedelta destination is not supported when already time travelling."
The name of the class is lowercase, so match that in error message.

```suggestion
                "timedelta destination is not supported when already time travelling."
```

2022-11-30 16:00 UTC, AgDude commented
@adamchainz I think your concerns have been addressed. Please clarify if I am still missing something.

2022-12-01 13:56 UTC, adamchainz commented
Yea sure, no need to comment, I’ll get around to reviewing at some point. Busy with life stuff atm.

2023-09-19 10:12 UTC, merged

2023-09-19 13:48 UTC, adamchainz commented
Thanks for this. I merged this with a few changes. I decided that blocking use of `timedelta` within a `travel()` block wasn't worth the complexity.

#247 was fixed by calling the existing `shift()` method, but this is still useful for cases like "do a thing, then move a bit into the future and assert some state changed".

Released in 2.13.0.